# Generated by Django 3.2.9 on 2022-02-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=25)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
